name: CD

on:
  push:
    branches: [ main ]
 
jobs:
  
  build:
    env: 
      CI: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build
    - name: Deploy
      run: |
        git config --global user.email "immortal.mind2016@gmail.com>"
        git config --global user.name "immortalmind2016>"
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/SaraHassanAboEldahab/English-Bo>.git
        yarn deploy

      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build